name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
          repository: Pscheidl/rust-kubernetes-operator-example
          ref: refs/heads/master
          path: rust-kubernetes-operator-example

      - name: Help
        run: make help

      - name: Build
        run: make build
