name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
          repository: Pscheidl/rust-kubernetes-operator-example
          ref: refs/heads/master
          path: rust-kubernetes-operator-example

      - name: Help
        run: make help

      - name: Cache Rust
        id: cache-rust
        uses: actions/cache@v3
        with:
          path: rust-kubernetes-operator-example/target/
          key: ${{ runner.os }}-rust-${{ hashFiles('rust-kubernetes-operator-example/target/CACHEDIR.TAG') }}

      - name: Build
        run: make build

      - name: kwok
        run: brew install kwok

      - name: Get kwok
        run: wget -O kwokctl -c "https://github.com/kubernetes-sigs/kwok/releases/download/v0.1.1/kwokctl-$(go env GOOS)-$(go env GOARCH)"

      - name: kwok
        run: chmod +x kwokctl

      - name: kwok
        run: sudo mv kwokctl /usr/local/bin/kwokctl

      - name: config
        run: make config
